import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET() {
  try {
    const cars = await prisma.car.findMany({ orderBy: { displayId: "asc" } });
    return NextResponse.json(cars);
  } catch {
    return NextResponse.json({ error: "Failed to fetch cars" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id, ...data } = body; // strip id — auto-generated by PostgreSQL
    const max = await prisma.car.findFirst({ orderBy: { displayId: "desc" }, select: { displayId: true } });
    const car = await prisma.car.create({
      data: { ...data, displayId: (max?.displayId ?? 0) + 1 },
    });
    return NextResponse.json(car);
  } catch {
    return NextResponse.json({ error: "Failed to create car" }, { status: 500 });
  }
}

export async function PUT(req: Request) {
  try {
    const body = await req.json();
    const { id, ...data } = body;
    const car = await prisma.car.update({ where: { id: Number(id) }, data });
    return NextResponse.json(car);
  } catch {
    return NextResponse.json({ error: "Failed to update car" }, { status: 500 });
  }
}

export async function DELETE(req: Request) {
  try {
    const { id } = await req.json();
    await prisma.car.delete({ where: { id: Number(id) } });
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Failed to delete car" }, { status: 500 });
  }
}
